#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'r2d2-arm-ctrl==0.7.0','console_scripts','subscriber_member_function'
__requires__ = 'r2d2-arm-ctrl==0.7.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('r2d2-arm-ctrl==0.7.0', 'console_scripts', 'subscriber_member_function')()
    )
